# Site settings
title: Villar Time-domain Astronomy Data Lab
email: ashleyvillar@cfa.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Villar Time-domain Astronomy Data Lab research website
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages
  - _members

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

collections:
  members:
    output: true

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
